;<?php die('');?>
isWindows=1
enableAllModules=
disableInstallers=
chmodDir=509
chmodFile=436
forceHTTPSPort=
forceHTTPPort=
fallbackLocale=
domainName=localhost
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="app:plugins/,lib:jelix-plugins/"
timeZone="Africa/Abidjan"
httpVersion=
theme=default
charset=UTF-8
locale=fr_FR
startAction="default:index"
startModule=link
[availableLocales]
0=fr_FR
1=en_US
[modules]
jelix.access=2
jacldb.access=0
jacl2db.access=0
jauth.access=2
jauthdb.access=0
junittests.access=0
jsoap.access=0
shop.access=2
catalog.access=2
order.access=2
shipping.access=2
customer.access=2
promo.access=2
blog.access=2
event.access=2
link.access=2
user.access=2
office.access=2
jelix.dbprofile=default
jacl.access=0
jacl.dbprofile=default
jacl2.access=0
jacl2.dbprofile=default
jacl2db.dbprofile=default
jacldb.dbprofile=default
jauth.dbprofile=default
jauthdb.dbprofile=default
jpref.access=0
jpref.dbprofile=default
jsoap.dbprofile=default
junittests.dbprofile=default
blog.dbprofile=default
link.dbprofile=default
office.dbprofile=default
user.dbprofile=default
[coordplugins]
auth="index/auth.coord.ini.php"
[tplplugins]
defaultJformsBuilder=html
[responses]
html=myHtmlResponse
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
sitemap=jResponseSitemap
csv=jResponseCsv
html2pdf=jResponseHtml2Pdf
html.path="C:\wamp\www\df/responses/myHtmlResponse.class.php"
basichtml.path="C:\wamp\www\df\lib\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="C:\wamp\www\df\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="C:\wamp\www\df\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="C:\wamp\www\df\lib\jelix/core/response/jResponseBinary.class.php"
text.path="C:\wamp\www\df\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="C:\wamp\www\df\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="C:\wamp\www\df\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="C:\wamp\www\df\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="C:\wamp\www\df\lib\jelix/core/response/jResponseXmlrpc.class.php"
xml.path="C:\wamp\www\df\lib\jelix/core/response/jResponseXml.class.php"
zip.path="C:\wamp\www\df\lib\jelix/core/response/jResponseZip.class.php"
rss2.0.path="C:\wamp\www\df\lib\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="C:\wamp\www\df\lib\jelix/core/response/jResponseAtom10.class.php"
css.path="C:\wamp\www\df\lib\jelix/core/response/jResponseCss.class.php"
htmlfragment.path="C:\wamp\www\df\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="C:\wamp\www\df\lib\jelix/core/response/jResponseHtml.class.php"
sitemap.path="C:\wamp\www\df\lib\jelix/core/response/jResponseSitemap.class.php"
csv.path="C:\wamp\www\df/modules/office/responses/jResponseCsv.class.php"
html2pdf.path="C:\wamp\www\df/modules/office/responses/jResponseHtml2Pdf.class.php"
[_coreResponses]
html=jResponseHtml
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
sitemap=jResponseSitemap
csv=jResponseCsv
html2pdf=jResponseHtml2Pdf
html.path="C:\wamp\www\df\lib\jelix/core/response/jResponseHtml.class.php"
basichtml.path="C:\wamp\www\df\lib\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="C:\wamp\www\df\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="C:\wamp\www\df\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="C:\wamp\www\df\lib\jelix/core/response/jResponseBinary.class.php"
text.path="C:\wamp\www\df\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="C:\wamp\www\df\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="C:\wamp\www\df\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="C:\wamp\www\df\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="C:\wamp\www\df\lib\jelix/core/response/jResponseXmlrpc.class.php"
xml.path="C:\wamp\www\df\lib\jelix/core/response/jResponseXml.class.php"
zip.path="C:\wamp\www\df\lib\jelix/core/response/jResponseZip.class.php"
rss2.0.path="C:\wamp\www\df\lib\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="C:\wamp\www\df\lib\jelix/core/response/jResponseAtom10.class.php"
css.path="C:\wamp\www\df\lib\jelix/core/response/jResponseCss.class.php"
htmlfragment.path="C:\wamp\www\df\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="C:\wamp\www\df\lib\jelix/core/response/jResponseHtml.class.php"
sitemap.path="C:\wamp\www\df\lib\jelix/core/response/jResponseSitemap.class.php"
csv.path="C:\wamp\www\df/modules/office/responses/jResponseCsv.class.php"
html2pdf.path="C:\wamp\www\df/modules/office/responses/jResponseHtml2Pdf.class.php"
[jResponseHtml]
plugins=debugbar
minifyEntryPoint=minify.php
minifyCSS=
minifyJS=
minifyExcludeCSS=
minifyExcludeJS="jelix/wymeditor/jquery.wymeditor.js"
[debugbar]
plugins="sqllog,sessiondata,defaultlog"
defaultPosition=right
errors_openon=error
[error_handling]
messageLogFormat="%date%\t%ip%\t[%code%]\t%msg%\t%file%\t%line%\n\t%url%\n%params%\n%trace%\n\n"
errorMessage="A technical error has occured (code: %code%). Sorry for this inconvenience."
[compilation]
checkCacheFiletime=1
force=
[urlengine]
engine=simple
enableParser=
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/df/"
backendBasePath=
checkHttpsOnParsing=1
jelixWWWPath="/df/jelix/"
jqueryPath="/df/jelix/jquery/"
defaultEntrypoint=index
notfoundAct="jelix~error:notfound"
simple_urlengine_https=
significantFile=urls.xml
urlScript="/df/index.php"
urlScriptPath="/df/"
urlScriptName=index.php
urlScriptId=index
urlScriptIdenc=index
documentRoot="C:/wamp/www/"
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
[logger]
_all=memory
default=file
error=file
warning=file
notice=file
deprecated=
strict=
debug=
sql=
soap=
[fileLogger]
default=messages.log
error=errors.log
warning=errors.log
notice=errors.log
deprecated=errors.log
strict=errors.log
debug=debug.log
[memorylogger]
default=20
error=10
warning=10
notice=10
deprecated=10
strict=10
debug=20
sql=20
soap=20
[mailLogger]
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
[mailer]
webmasterEmail="webmaster@gouabo.com"
webmasterName=" Service Technique GOUABO"
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
filesDir="mails/"
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
copyToFiles=
[acl]
driver=
[acl2]
driver=
[sessions]
start=1
shared_session=
name=
storage=files
loadClasses=
files_path="var/sessions/"
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[jforms_builder_html]
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/js/jforms/htmleditors/wymeditor_default.js"
default.skin.default="jelix/wymeditor/skins/default/skin.css"
wymbasic.engine.name=wymeditor
wymbasic.engine.file[]="jelix/jquery/jquery.js"
wymbasic.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
wymbasic.config="jelix/js/jforms/htmleditors/wymeditor_basic.js"
wymbasic.skin.default="jelix/wymeditor/skins/default/skin.css"
ckdefault.engine.name=ckeditor
ckdefault.engine.file[]="jelix/ckeditor/ckeditor.js"
ckdefault.config="jelix/js/jforms/htmleditors/ckeditor_default.js"
ckfull.engine.name=ckeditor
ckfull.engine.file[]="jelix/ckeditor/ckeditor.js"
ckfull.config="jelix/js/jforms/htmleditors/ckeditor_full.js"
ckbasic.engine.name=ckeditor
ckbasic.engine.file[]="jelix/ckeditor/ckeditor.js"
ckbasic.config="jelix/js/jforms/htmleditors/ckeditor_basic.js"
[wikieditors]
default.engine.name=wr3
default.wiki.rules=wr3_to_xhtml
default.engine.file="jelix/markitup/jquery.markitup.js"
default.config.path="jelix/markitup/sets/wr3/"
default.image.path="jelix/markitup/sets/wr3/images/"
default.skin="jelix/markitup/skins/simple/style.css"
[zones]
disableCache=
[classbindings]
[imagemodifier]
src_url=
src_path=
cache_url=
cache_path=
[rootUrls]
jelix.cache="cache/"
[langToLocale]
en=en_US
fr=fr_FR
[disabledListeners]
[shop]
product_taxes=include
[_allBasePath]
0="C:\wamp\www\df\lib/jelix-modules/"
1="C:\wamp\www\df/modules/"
2="C:\wamp\www\df/plugins/auth/"
3="C:\wamp\www\df/plugins/coord/"
4="C:\wamp\www\df/plugins/db/"
5="C:\wamp\www\df/plugins/tpl/"
6="C:\wamp\www\df\lib/jelix-plugins/cache/"
7="C:\wamp\www\df\lib/jelix-plugins/kvdb/"
[_modulesPathList]
jelix="C:\wamp\www\df\lib\jelix/core-modules/jelix/"
jauth="C:\wamp\www\df\lib/jelix-modules/jauth/"
blog="C:\wamp\www\df/modules/blog/"
link="C:\wamp\www\df/modules/link/"
office="C:\wamp\www\df/modules/office/"
user="C:\wamp\www\df/modules/user/"
[_pluginsPathList_auth]
class="C:\wamp\www\df\lib\jelix/plugins/auth/class/"
db="C:\wamp\www\df\lib\jelix/plugins/auth/db/"
ldap="C:\wamp\www\df\lib\jelix/plugins/auth/ldap/"
lds="C:\wamp\www\df\lib\jelix/plugins/auth/lds/"
[_pluginsPathList_cache]
db="C:\wamp\www\df\lib\jelix/plugins/cache/db/"
memcache="C:\wamp\www\df\lib\jelix/plugins/cache/memcache/"
memcache22="C:\wamp\www\df\lib\jelix/plugins/cache/memcache22/"
file="C:\wamp\www\df\lib/jelix-plugins/cache/file/"
[_pluginsPathList_configcompiler]
debugbar="C:\wamp\www\df\lib\jelix/plugins/configcompiler/debugbar/"
locales="C:\wamp\www\df\lib\jelix/plugins/configcompiler/locales/"
nsautoloader="C:\wamp\www\df\lib\jelix/plugins/configcompiler/nsautoloader/"
responses="C:\wamp\www\df\lib\jelix/plugins/configcompiler/responses/"
session="C:\wamp\www\df\lib\jelix/plugins/configcompiler/session/"
[_pluginsPathList_coord]
auth="C:\wamp\www\df\lib\jelix/plugins/coord/auth/"
autolocale="C:\wamp\www\df\lib\jelix/plugins/coord/autolocale/"
history="C:\wamp\www\df\lib\jelix/plugins/coord/history/"
traceexec="C:\wamp\www\df\lib\jelix/plugins/coord/traceexec/"
zendframework="C:\wamp\www\df\lib\jelix/plugins/coord/zendframework/"
[_pluginsPathList_db]
mssql="C:\wamp\www\df\lib\jelix/plugins/db/mssql/"
mysql="C:\wamp\www\df\lib\jelix/plugins/db/mysql/"
mysqli="C:\wamp\www\df\lib\jelix/plugins/db/mysqli/"
oci="C:\wamp\www\df\lib\jelix/plugins/db/oci/"
pgsql="C:\wamp\www\df\lib\jelix/plugins/db/pgsql/"
sqlite="C:\wamp\www\df\lib\jelix/plugins/db/sqlite/"
sqlite3="C:\wamp\www\df\lib\jelix/plugins/db/sqlite3/"
[_pluginsPathList_debugbar]
defaultlog="C:\wamp\www\df\lib\jelix/plugins/debugbar/defaultlog/"
sessiondata="C:\wamp\www\df\lib\jelix/plugins/debugbar/sessiondata/"
soaplog="C:\wamp\www\df\lib\jelix/plugins/debugbar/soaplog/"
sqllog="C:\wamp\www\df\lib\jelix/plugins/debugbar/sqllog/"
[_pluginsPathList_formbuilder]
html="C:\wamp\www\df\lib\jelix/plugins/formbuilder/html/"
[_pluginsPathList_formwidget]
button_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/button_html/"
captcha_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/captcha_html/"
checkboxes_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/checkboxes_html/"
checkbox_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/checkbox_html/"
choice_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/choice_html/"
datetime_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/datetime_html/"
date_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/date_html/"
group_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/group_html/"
html="C:\wamp\www\df\lib\jelix/plugins/formwidget/html/"
htmleditor_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/htmleditor_html/"
input_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/input_html/"
listbox_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/listbox_html/"
menulist_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/menulist_html/"
output_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/output_html/"
radiobuttons_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/radiobuttons_html/"
reset_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/reset_html/"
secretconfirm_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/secretconfirm_html/"
secret_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/secret_html/"
submit_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/submit_html/"
textarea_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/textarea_html/"
upload_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/upload_html/"
wikieditor_html="C:\wamp\www\df\lib\jelix/plugins/formwidget/wikieditor_html/"
[_pluginsPathList_htmlresponse]
debugbar="C:\wamp\www\df\lib\jelix/plugins/htmlresponse/debugbar/"
minify="C:\wamp\www\df\lib\jelix/plugins/htmlresponse/minify/"
[_pluginsPathList_jforms]
html="C:\wamp\www\df\lib\jelix/plugins/jforms/html/"
htmllight="C:\wamp\www\df\lib\jelix/plugins/jforms/htmllight/"
[_pluginsPathList_kvdb]
db="C:\wamp\www\df\lib\jelix/plugins/kvdb/db/"
dba="C:\wamp\www\df\lib\jelix/plugins/kvdb/dba/"
file2="C:\wamp\www\df\lib\jelix/plugins/kvdb/file2/"
memcache="C:\wamp\www\df\lib\jelix/plugins/kvdb/memcache/"
redis="C:\wamp\www\df\lib\jelix/plugins/kvdb/redis/"
file="C:\wamp\www\df\lib/jelix-plugins/kvdb/file/"
[_pluginsPathList_logger]
firebug="C:\wamp\www\df\lib\jelix/plugins/logger/firebug/"
[_tplpluginsPathList_common]
0="C:\wamp\www\df/plugins/tpl/common/"
1="C:\wamp\www\df\lib\jelix/plugins/tpl/common/"
[_tplpluginsPathList_html]
0="C:\wamp\www\df/plugins/tpl/html/"
1="C:\wamp\www\df\lib\jelix/plugins/tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="C:\wamp\www\df\lib\jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="C:\wamp\www\df/plugins/tpl/text/"
1="C:\wamp\www\df\lib\jelix/plugins/tpl/text/"
[_tplpluginsPathList_xml]
0="C:\wamp\www\df\lib\jelix/plugins/tpl/xml/"
[_pluginsPathList_urls]
basic_significant="C:\wamp\www\df\lib\jelix/plugins/urls/basic_significant/"
significant="C:\wamp\www\df\lib\jelix/plugins/urls/significant/"
simple="C:\wamp\www\df\lib\jelix/plugins/urls/simple/"
[_autoload_class]
[_autoload_namespace]
[_autoload_classpattern]
[_autoload_includepathmap]
[_autoload_includepath]
[_autoload_namespacepathmap]
[_autoload_autoloader]
